version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Qwer1234@
      MYSQL_DATABASE: new_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - backend
    environment:
      NODE_ENV: production
      DIRECT_DB_CONNECTION: mysql://root:Qwer1234@@db:3306/new_db
    command: >
      dockerize -wait tcp://db:3306 -timeout 30s &&
      npx prisma migrate deploy &&
      node dist/src/server.js


networks:
  backend:
    driver: bridge

volumes:
  db_data:
